# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84975c351b2f931c32a0938d1b43400f402896c8a0f71b125c8b202bfb83d226d1b6f568e5ac6c5486dc66372f97fcce45027088c020bbfd4cc0fd4faf7390ea

test:
  secret_key_base: fdc033c67cc28efa864c1f25e32672f3d22f68256f34bb0c3d4ad3882f70b146d00f9a77f8432e20bec1dd668d855a44690aee06b5c3155bef6459a016861902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
